languageCode = "en"
DefaultContentLanguage = "en"
title = "1337.coffee"
theme = 'risotto'
license = 'MIT'
description = 'Sharing what I like and write'
name = "1337.coffee"
tags = ["pentest", "web", "ad", "redteam", "red team", "active directory", "javascript"]
paginate = 3

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

sectionPagesMenu = "main"
enableInlineShortcodes = true

[params]
noindex = false

[menu]

  [[menu.main]]
    identifier = "main"
    name = "Home"
    url = "/"
    weight = 1

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/oppsec/"

[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "GitHub"
url = "https://x.com/opps3c"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "GitHub"
url = "https://www.linkedin.com/in/dansdm/"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params.theme]
palette = "material"

# Sidebar: about/bio
[params.about]
title = "About me"
description = "Pentester at Brazilian company, Python developer in free time and eWPTX, CEH Practical certified."
# unicode/emoji logo:
logo = "☕️"
# or use an image:
#logo_image = "images/rice.svg"